version: '3.8'

services:
  bca-backend:
    build: .
    container_name: bca-backend
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
    # network_mode: host # Uncomment se o SDK estiver noutra stack e for usar host mode
    
    # Exemplo do que adicionar no seu compose principal para remover o mock e apontar para este
    # networks:
    #   mojaloop-net:
    #     aliases:
    #       - bca-backend

