server:
  port: 8081

fsp:
  id: bca
  currency: CVE

spring:
  application:
    name: bca
  datasource:
    url: jdbc:postgresql://postgres:5432/bcacore
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    com.bca.api: DEBUG
    org.springframework.web: INFO

sdk:
  outbound:
    url: http://63.250.58.252:4001

tp:
  api:
    url: http://tp-api-svc.kretxeucv.cv

fee:
  percentage: 1.0   # taxa em percentagem do montante (ex: 1.0 = 1%)
  currency: CVE

fx:
  rates:
    EUR: 110.20
    USD: 101.50
    GBP: 128.40
    BRL: 19.80

